// Wireflow and User Flow definitions, one per user goal.
// Node position: c = column, r = row in the flow grid. Screen ids match app/*.js.
window.FLOWS = {
  // ───────── Segment 1 · Comprador Moderno (persona: Juan López) ─────────
  'g1-start-session': {
    title: 'User goal 1 · Start a shopping session with a budget',
    persona: 'Juan López, Comprador Moderno (Segment 1)',
    stories: 'US04 · TS02',
    goal: 'As a shopper, I want to take a cart, link it and set a spending limit so I can start shopping knowing how much I can spend.',
    wireflow: [
      [['cd-welcome', 'Tap “Tap to start”'], ['cd-budget', 'Type S/ 150, tap “Start shopping”'], ['cd-session', '']],
      [['ma-home', 'Tap “Link a cart”'], ['ma-pair', 'Camera reads cart code'], ['ma-budget', 'Tap “Start shopping”'], ['ma-cart', '']],
    ],
    wireflowLinks: [['cd-welcome', 'ma-pair', 'Shopper scans the cart QR with the app']],
    nodes: [
      { id: 's', type: 'start', label: 'Shopper takes a cart', c: 0, r: 0 },
      { id: 'w', type: 'screen', screen: 'cd-welcome', c: 1, r: 0 },
      { id: 'd1', type: 'decision', label: 'Uses the app?', c: 2, r: 0 },
      { id: 'b', type: 'screen', screen: 'cd-budget', c: 3, r: 0 },
      { id: 'd2', type: 'decision', label: 'Amount valid?', c: 4, r: 0 },
      { id: 'ss', type: 'screen', screen: 'cd-session', c: 5, r: 0 },
      { id: 'e', type: 'end', label: 'Session active', c: 6, r: 0 },
      { id: 'err', type: 'action', label: 'Field turns red: “Enter an amount greater than S/ 0”', c: 4, r: 1, tone: 'err' },
      { id: 'p', type: 'screen', screen: 'ma-pair', c: 2, r: 1 },
      { id: 'd3', type: 'decision', label: 'Code detected?', c: 2, r: 2 },
      { id: 'man', type: 'action', label: 'Types the 4-digit cart code', c: 1, r: 2, tone: 'err' },
      { id: 'mb', type: 'screen', screen: 'ma-budget', c: 3, r: 2 },
    ],
    edges: [
      ['s', 'w', ''], ['w', 'd1', 'Tap to start'], ['d1', 'b', 'No'], ['b', 'd2', 'Start shopping'], ['d2', 'ss', 'Yes / Skip'], ['ss', 'e', ''],
      ['d2', 'err', 'No', 'alt', 'b-t'], ['err', 'b', 'Retry', 'alt', 'l-b'],
      ['d1', 'p', 'Yes · scans QR', 'happy', 'b-t'], ['p', 'd3', '', 'happy', 'b-t'], ['d3', 'mb', 'Yes', 'happy', 'r-l'], ['d3', 'man', 'No', 'alt', 'l-r'], ['man', 'mb', 'Link', 'alt', 'b-b'],
      ['mb', 'ss', 'Budget synced to cart', 'happy', 'r-b'],
    ],
  },

  'g2-track-total': {
    title: 'User goal 2 · Add products and keep the total under control',
    persona: 'Juan López, Comprador Moderno (Segment 1)',
    stories: 'US05 · US06 · US07 · US09 · US10',
    goal: 'As a shopper, I want every product I drop in or take out to update my total so I never go over my budget.',
    wireflow: [
      [['cd-session', 'Drops a product (RFID + weight OK)'], ['cd-threshold', 'Taps “Edit budget” or removes an item'], ['cd-removed', '']],
      [['cd-session', 'Weight added without a tag read'], ['cd-discrepancy', 'Places the item again'], ['cd-session', '']],
      [['cd-session', 'Tag not in catalog'], ['cd-unknown', 'Places it again'], ['cd-session', '']],
    ],
    nodes: [
      { id: 's', type: 'start', label: 'Session active', c: 0, r: 0 },
      { id: 'ss', type: 'screen', screen: 'cd-session', c: 1, r: 0 },
      { id: 'd1', type: 'decision', label: 'RFID tag recognized?', c: 2, r: 0 },
      { id: 'd2', type: 'decision', label: 'Weight within tolerance?', c: 3, r: 0 },
      { id: 'd3', type: 'decision', label: 'Total ≥ 90% of budget?', c: 4, r: 0 },
      { id: 'th', type: 'screen', screen: 'cd-threshold', c: 5, r: 0 },
      { id: 'rm', type: 'screen', screen: 'cd-removed', c: 6, r: 0 },
      { id: 'e', type: 'end', label: 'Ready to pay', c: 6, r: 1 },
      { id: 'uk', type: 'screen', screen: 'cd-unknown', c: 2, r: 1 },
      { id: 'dc', type: 'screen', screen: 'cd-discrepancy', c: 3, r: 1 },
      { id: 'd4', type: 'decision', label: 'Fixed by shopper?', c: 3, r: 2 },
      { id: 'sup', type: 'action', label: 'Supervisor verifies and unlocks (User goal 4)', c: 4, r: 2, tone: 'err' },
    ],
    edges: [
      ['s', 'ss', ''], ['ss', 'd1', 'Drops product'], ['d1', 'd2', 'Yes'], ['d2', 'd3', 'Yes · item added'], ['d3', 'th', 'Yes'], ['th', 'rm', 'Removes item'], ['rm', 'e', '', 'happy', 'b-t'],
      ['d3', 'e', 'No · keeps shopping', 'happy', 'b-l'],
      ['d1', 'uk', 'No', 'alt', 'b-t'], ['uk', 'ss', 'Places it again', 'alt', 'l-b'],
      ['d2', 'dc', 'No · payment paused', 'alt', 'b-t'], ['dc', 'd4', '', 'alt', 'b-t'], ['d4', 'ss', 'Yes', 'alt', 'l-b'], ['d4', 'sup', 'No', 'alt', 'r-l'],
    ],
  },

  'g3-pay-and-exit': {
    title: 'User goal 3 · Pay with QR and leave the store',
    persona: 'Juan López, Comprador Moderno (Segment 1)',
    stories: 'US08 · US12 · TS03',
    goal: 'As a shopper, I want to pay from the cart with Yape or Plin and walk out without stopping at a cashier.',
    wireflow: [
      [['cd-session', 'Taps “Proceed to payment”'], ['cd-checkout', 'Scans QR with Yape'], ['cd-paid', 'Taps “Finish and release cart”'], ['cd-welcome', '']],
      [['ma-cart', 'Taps “Pay S/ 76.60”'], ['ma-pay', 'Chooses Yape and pays'], ['ma-receipt', '']],
    ],
    nodes: [
      { id: 's', type: 'start', label: 'Ready to pay', c: 0, r: 0 },
      { id: 'ss', type: 'screen', screen: 'cd-session', c: 1, r: 0 },
      { id: 'd1', type: 'decision', label: 'Open discrepancies?', c: 2, r: 0 },
      { id: 'd2', type: 'decision', label: 'Pays from?', c: 3, r: 0 },
      { id: 'co', type: 'screen', screen: 'cd-checkout', c: 4, r: 0 },
      { id: 'd3', type: 'decision', label: 'Webhook confirms before QR expires?', c: 5, r: 0 },
      { id: 'pd', type: 'screen', screen: 'cd-paid', c: 6, r: 0 },
      { id: 'd4', type: 'decision', label: 'Crosses exit with clearance?', c: 7, r: 0 },
      { id: 'e', type: 'end', label: 'Leaves the store', c: 8, r: 0 },
      { id: 'dc', type: 'screen', screen: 'cd-discrepancy', c: 2, r: 1 },
      { id: 'mp', type: 'screen', screen: 'ma-pay', c: 3, r: 1 },
      { id: 'exp', type: 'action', label: 'QR expired: “Generate a new code” returns to checkout', c: 5, r: -1, tone: 'err' },
      { id: 'rc', type: 'screen', screen: 'ma-receipt', c: 6, r: 1 },
      { id: 'lock', type: 'action', label: 'Wheels lock, alarm sounds, alert to Console (User goal 4)', c: 7, r: 1, tone: 'err' },
    ],
    edges: [
      ['s', 'ss', ''], ['ss', 'd1', 'Proceed to payment'], ['d1', 'd2', 'No'], ['d2', 'co', 'Cart screen'], ['co', 'd3', 'Scans QR'], ['d3', 'pd', 'Yes'], ['pd', 'd4', 'Walks to exit'], ['d4', 'e', 'Yes'],
      ['d1', 'dc', 'Yes', 'alt', 'b-t'], ['dc', 'ss', 'Fixed', 'alt', 'l-b'],
      ['d2', 'mp', 'Mobile app', 'happy', 'b-t'], ['mp', 'd3', 'Pays in Yape', 'happy', 'r-b'],
      ['d3', 'exp', 'No', 'alt', 't-b'], ['exp', 'co', 'Retry', 'alt', 'l-t'],
      ['pd', 'rc', 'Receipt synced', 'happy', 'b-t'],
      ['d4', 'lock', 'No', 'alt', 'b-t'],
    ],
  },

  // ───────── Segment 2 · Administrador de Tienda (persona: Lucía) ─────────
  'g4-resolve-discrepancy': {
    title: 'User goal 4 · Resolve a weight discrepancy from the Console',
    persona: 'Lucía, Administrador de Tienda / Operaciones (Segment 2)',
    stories: 'US09 · US10 · US11',
    goal: 'As a floor supervisor, I want to see which cart has a weight discrepancy and unlock it after checking it, so the shopper can keep buying and no unpaid item leaves.',
    wireflow: [
      [['wa-login', 'Signs in'], ['wa-dashboard', 'Clicks the live alert'], ['wa-cart-detail', 'Clicks “Verify and unlock”'], ['wa-unlock', 'Enters resolution + PIN'], ['wa-carts', '']],
      [['wa-alerts', 'Clicks “Open cart”'], ['wa-cart-detail', '']],
    ],
    nodes: [
      { id: 's', type: 'start', label: 'Alert raised by the edge', c: 0, r: 0 },
      { id: 'lg', type: 'screen', screen: 'wa-login', c: 1, r: 0 },
      { id: 'd0', type: 'decision', label: 'Credentials valid?', c: 2, r: 0 },
      { id: 'db', type: 'screen', screen: 'wa-dashboard', c: 3, r: 0 },
      { id: 'dt', type: 'screen', screen: 'wa-cart-detail', c: 4, r: 0 },
      { id: 'd1', type: 'decision', label: 'Item verified in person?', c: 5, r: 0 },
      { id: 'ul', type: 'screen', screen: 'wa-unlock', c: 6, r: 0 },
      { id: 'd2', type: 'decision', label: 'PIN valid?', c: 7, r: 0 },
      { id: 'ct', type: 'screen', screen: 'wa-carts', c: 8, r: 0 },
      { id: 'e', type: 'end', label: 'Cart back in session', c: 9, r: 0 },
      { id: 'le', type: 'action', label: '“Wrong email or password”, 5 tries then account lock', c: 2, r: 1, tone: 'err' },
      { id: 'al', type: 'screen', screen: 'wa-alerts', c: 3, r: 1 },
      { id: 'fl', type: 'action', label: 'Adds audit flag; cart stays locked until items are re-checked', c: 5, r: 1, tone: 'err' },
      { id: 'pe', type: 'action', label: '“Incorrect PIN”, field cleared', c: 7, r: 1, tone: 'err' },
    ],
    edges: [
      ['s', 'lg', ''], ['lg', 'd0', 'Sign in'], ['d0', 'db', 'Yes'], ['db', 'dt', 'Opens alert'], ['dt', 'd1', 'Goes to the cart'], ['d1', 'ul', 'Yes'], ['ul', 'd2', 'Unlock cart'], ['d2', 'ct', 'Yes'], ['ct', 'e', ''],
      ['d0', 'le', 'No', 'alt', 'b-t'], ['le', 'lg', 'Retry', 'alt', 'l-b'],
      ['db', 'al', 'Alerts menu', 'happy', 'b-t'], ['al', 'dt', 'Open cart', 'happy', 'r-b'],
      ['d1', 'fl', 'No', 'alt', 'b-t'],
      ['d2', 'pe', 'No', 'alt', 'b-t'], ['pe', 'ul', 'Retry', 'alt', 'l-b'],
    ],
  },

  'g5-update-tolerance': {
    title: 'User goal 5 · Update a product’s price, weight and tolerance',
    persona: 'Lucía, Administrador de Tienda / Operaciones (Segment 2)',
    stories: 'US13',
    goal: 'As a store administrator, I want to adjust a product’s nominal weight and tolerance so the carts stop raising false discrepancies for it.',
    wireflow: [
      [['wa-dashboard', 'Clicks “Catalog”'], ['wa-catalog', 'Searches SKU, clicks edit'], ['wa-catalog-edit', 'Sets tolerance 6%, “Save and sync”'], ['wa-catalog', '']],
    ],
    nodes: [
      { id: 's', type: 'start', label: 'False alerts on a SKU', c: 0, r: 0 },
      { id: 'db', type: 'screen', screen: 'wa-dashboard', c: 1, r: 0 },
      { id: 'ca', type: 'screen', screen: 'wa-catalog', c: 2, r: 0 },
      { id: 'd1', type: 'decision', label: 'Product found?', c: 3, r: 0 },
      { id: 'ed', type: 'screen', screen: 'wa-catalog-edit', c: 4, r: 0 },
      { id: 'd2', type: 'decision', label: 'Values valid?', c: 5, r: 0 },
      { id: 'd3', type: 'decision', label: 'Edge sync OK?', c: 6, r: 0 },
      { id: 'e', type: 'end', label: 'New rule active in 40 carts', c: 7, r: 0 },
      { id: 'np', type: 'action', label: '“No results”: clear filters or “Add product”', c: 3, r: 1, tone: 'err' },
      { id: 've', type: 'action', label: 'Inline error: tolerance must be 0–15%, weight > 0 g', c: 5, r: 1, tone: 'err' },
      { id: 'se', type: 'action', label: 'Saved in cloud; banner “3 carts pending sync”, retried automatically', c: 6, r: 1, tone: 'err' },
    ],
    edges: [
      ['s', 'db', ''], ['db', 'ca', 'Catalog'], ['ca', 'd1', 'Search SKU'], ['d1', 'ed', 'Yes · edit'], ['ed', 'd2', 'Save and sync'], ['d2', 'd3', 'Yes'], ['d3', 'e', 'Yes'],
      ['d1', 'np', 'No', 'alt', 'b-t'], ['np', 'ca', 'New search', 'alt', 'l-b'],
      ['d2', 've', 'No', 'alt', 'b-t'], ['ve', 'ed', 'Fix values', 'alt', 'l-b'],
      ['d3', 'se', 'No', 'alt', 'b-t'], ['se', 'e', 'Sync completes', 'alt', 'r-b'],
    ],
  },
};
